AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Stack to create a ECR holding the container image for pipeline acceptance tests

Resources:
  ECR:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: pipeline-test-image
      ImageTagMutability: MUTABLE
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Retain 10 untagged images",
                "selection": {
                  "tagStatus": "untagged",
                  "countType": "imageCountMoreThan",
                  "countNumber": 10
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }
      RepositoryPolicyText:
        Version: 2012-10-17
        Statement:
          - Sid: AllowAccountToPull
            Effect: Allow
            Principal: "*"
            Action:
              - "ecr:BatchCheckLayerAvailability"
              - "ecr:BatchGetImage"
              - "ecr:DescribeImages"
              - "ecr:DescribeRepositories"
              - "ecr:GetDownloadUrlForLayer"
              - "ecr:GetLifecyclePolicy"
              - "ecr:GetLifecyclePolicyPreview"
              - "ecr:GetRepositoryPolicy"
              - "ecr:ListImages"
            Condition:
              StringEquals:
                "aws:PrincipalOrgID":
                  - o-pjzf8d99ys
                  - o-dpp53lco28

  GitHubActionsRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action: "sts:AssumeRoleWithWebIdentity"
            Principal:
              Federated: !ImportValue GitHubIdentityProviderArn
            Condition:
              StringLike:
                "token.actions.githubusercontent.com:sub":
                  - !Sub "repo:govuk-one-login/orchestration-acceptance-tests*ref:refs/heads/main"

  TestRunnerImageRepositoryPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName:
        Fn::Join:
          - "-"
          - - !Ref AWS::StackName
            - "TestRunnerImageRepositoryPolicy"
            - Fn::Select:
                - 4
                - Fn::Split:
                    - "-"
                    - Fn::Select:
                        - 2
                        - Fn::Split:
                            - "/"
                            - Ref: AWS::StackId
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Sid: ListImagesInRepository
            Action:
              - "ecr:ListImages"
            Resource:
              - !GetAtt ECR.Arn
          - Effect: Allow
            Sid: ManageRepositoryContents
            Action:
              - "ecr:BatchCheckLayerAvailability"
              - "ecr:GetDownloadUrlForLayer"
              - "ecr:GetRepositoryPolicy"
              - "ecr:DescribeRepositories"
              - "ecr:ListImages"
              - "ecr:DescribeImages"
              - "ecr:BatchGetImage"
              - "ecr:InitiateLayerUpload"
              - "ecr:UploadLayerPart"
              - "ecr:CompleteLayerUpload"
              - "ecr:PutImage"
            Resource:
              - !GetAtt ECR.Arn
          - Effect: "Allow"
            Sid: "AccessToECR"
            Action:
              - "ecr:GetAuthorizationToken"
            Resource: "*"
      Roles:
        - !Ref GitHubActionsRole
